### ISSUE TITLE
"An Internal Error Has Occurred.","url":"\/events\/restSearch" PyMISP 2.4.138

### ISSUE THREAD

**Issue by smclinden** [MISP/PyMISP#707]
Seeing an error with pymisp and the Rest API:

```
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}
CRITICAL:pymisp:Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.138 - Python 3.7', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'AUTH_KEY', 'Cookie': 'MISP-5e6a313d-3ae4-4e16-aa91-0cf90adf8275=01jtmonq4pk293rpbvlb4detk4'}
Request body:
None
Response (if any):
```

The only issue with diagnostics is:

```

Table name | Description | Expected schema | Actual schema |  
-- | -- | -- | -- | --
cerebrates
Column `description` is different | description YES text 65535 utf8mb4_unicode_ci text NULL | description YES text 65535 utf8mb4_unicode_ci text
```

**Comment by chrisinmtown** [comment]
Can you reproduce this easily?  When you do, immediately check the server's error.log file in directory `/var/www/MISP/app/tmp/logs`. The MISP server unfortunately takes a 500 internal server error on some invalid user requests, and you have to read the log messages to figure out what you did wrong.

**Comment by Rafiot** [comment]
@smclinden it would also be useful to know the request you're making.

**Comment by chrisinmtown** [comment]
@Rafiot in the original comment the request body is shown as None, as if it was empty.  Does the server handle an empty request body gracefully?

**Comment by Rafiot** [comment]
Oh, right, I missed that. 

I think it does, but then it returns the whole DB, so the error is probably because the server ran out of memory.

**Comment by smclinden** [comment]
This is the OpenCTI connector:

```
INFO:root:Fetching MISP events with args: {"tags": {"OR": ["opencti:import", "type:osint"]}, "publish_timestamp": 1614365695, "limit": 50, "page": 1}
CRITICAL [api.py:3180 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.138 - Python 3.7', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'C1ZJMBh74r2gBDeO4VnoCQWjP
Ur97r9tmAunl62M', 'Cookie': 'MISP-5e6a313d-3ae4-4e16-aa91-0cf90adf8275=4k2okvbcn5nn617tg1fsea1mm9'}
Request body:
None
Response (if any):
```

**Comment by Rafiot** [comment]
okay. So I imagine it is this code: https://github.com/OpenCTI-Platform/connectors/blob/master/misp/src/misp.py#L147

Did it work before, with an other query? Have you opened an issue on their side?

**Comment by smclinden** [comment]
AFAIK, it has never worked. I know that there was some internal discussion about using publish_timestamp versus timestamp (the latter being the old behavior).

Here is the config.yml. The publish_timestamp appears to be the current (at the time that the connector is run) Unix datetime.

```
misp:
  url: 'http://10.223.130.117' # Required
  key: 'AUTH_KEY' # Required
  ssl_verify: False # Required
  datetime_attribute: 'publish_timestamp' # Required, filter to be used in query for new MISP events
  create_reports: True # Required, create report for MISP event
  create_indicators: True # Required, create indicators for attributes
  create_observables: True # Required, create observables for attributes
  report_class: 'misp-event' # Optional, report_class if creating report for event
  import_from_date: '2021-01-01' # Optional, import all event from this date
  import_tags: 'opencti:import,type:osint' # Optional, list of tags used for import events
  import_tags_not: '' # Optional, list of tags to not include
  import_creator_orgs: 'CIRCL,Luatix' # Optional, only import events created by this ORG (put the identifier here)
  import_owner_orgs: 'CIRCL' # Optional, only import events owned by this ORG (put the identifier here)
```


```
INFO:root:Listing Threat-Actors with filters null.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4000
DEBUG:urllib3.connectionpool:http://localhost:4000 "POST /graphql HTTP/1.1" 200 144
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4000
DEBUG:urllib3.connectionpool:http://localhost:4000 "POST /graphql HTTP/1.1" 200 463
INFO:root:Connector registered with ID:CONNECTOR_UUID
INFO:root:Starting ping alive thread
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4000
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.223.130.117:80
DEBUG:urllib3.connectionpool:http://10.223.130.117:80 "GET /servers/getPyMISPVersion.json HTTP/1.1" 302 236
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.223.130.117:443
DEBUG:urllib3.connectionpool:https://10.223.130.117:443 "GET /servers/getPyMISPVersion.json HTTP/1.1" 200 23
DEBUG:urllib3.connectionpool:http://10.223.130.117:80 "GET /servers/getVersion HTTP/1.1" 302 225
DEBUG:urllib3.connectionpool:https://10.223.130.117:443 "GET /servers/getVersion HTTP/1.1" 200 87
DEBUG:urllib3.connectionpool:http://10.223.130.117:80 "GET /users/view/me HTTP/1.1" 302 220
DEBUG:urllib3.connectionpool:http://localhost:4000 "POST /graphql HTTP/1.1" 200 120
DEBUG:urllib3.connectionpool:https://10.223.130.117:443 "GET /users/view/me HTTP/1.1" 200 4375
DEBUG:urllib3.connectionpool:http://10.223.130.117:80 "GET /attributes/describeTypes.json HTTP/1.1" 302 236
DEBUG:urllib3.connectionpool:https://10.223.130.117:443 "GET /attributes/describeTypes.json HTTP/1.1" 200 21868
INFO:root:Initiate work for CONNECTOR_ID
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4000
DEBUG:urllib3.connectionpool:http://localhost:4000 "POST /graphql HTTP/1.1" 200 81
INFO:root:Connector last run: 2021-02-26 19:25:29

INFO:root:Fetching MISP events with args: {"tags": {"OR": ["opencti:import", "type:osint"]}, "publish_timestamp": 1614385529, "limit": 50, "page": 1}. <-- This is what is executed at L210

DEBUG:urllib3.connectionpool:http://10.223.130.117:80 "POST /events/restSearch HTTP/1.1" 302 224
DEBUG:urllib3.connectionpool:https://10.223.130.117:443 "GET /events/restSearch HTTP/1.1" 500 117
CRITICAL [api.py:3180 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.138 - Python 3.7', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'AUTH_CODE', 'Cookie': 'MISP-5e6a313d-3ae4-4e16-aa91-0cf90adf8275=ec9rcsfjt7ldii5co4n6bd4apk'}
Request body:
None
Response (if any):
