### ISSUE TITLE
Embedded backslashes in attribute value vanish after adding to event

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/PyMISP#723]
How can I preserve backslashes in attribute values when I add an attribute to an existing event?  The backslashes don't make it to the database.  I don't see any messages in debug.log/error.log, and the PyMISP.add_attribute() invocation returns success.  I'm using PyMISP 2.4.137 and the code basically is this:

```
    attr = pymisp.MISPAttribute()
    attr.type = aType
    attr.value = aValue
    attr.category = aCategory
    r = misp.add_attribute(event['Event']['id'], attr)
```

Here is the value that I read from an external source:
```
http://googlechromeupdater.twilightparadox.com/html?DVXNSTHORF=fd6f240590734406be3bd35ca3622ea0;GRIBOOZ0LN=a3bf23855b0b40dda08f709fabb60d32;\..\..\..\./mshtml,RunHTMLApplication
```

The value stored in the database has no backslashes:
```
mysql> select * from attributes where id = 154926899 \G
*************************** 1. row ***************************
                 id: 154926899
           event_id: 193076
          object_id: 0
    object_relation: NULL
           category: Network activity
               type: url
             value1: http://googlechromeupdater.twilightparadox.com/html?DVXNSTHORF=fd6f240590734406be3bd35ca3622ea0;GRIBOOZ0LN=a3bf23855b0b40dda08f709fabb60d32;......./mshtml,RunHTMLApplication
             value2: 
             to_ids: 1
               uuid: 8edb38f3-e3be-4f76-ac0f-784c154a3756
          timestamp: 1615908632
       distribution: 5
   sharing_group_id: 0
            comment: 
            deleted: 0
disable_correlation: 0
         first_seen: NULL
          last_seen: NULL
1 row in set (0.00 sec)
```
